# Generated by Django 4.1.4 on 2022-12-24 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Bio', models.TextField()),
                ('Picture', models.ImageField(default='', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EpisodeTitle', models.CharField(max_length=100)),
                ('EpisodeNumber', models.IntegerField()),
                ('EpisodeDuration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MovieTitle', models.CharField(max_length=100)),
                ('ReleaseDate', models.DateField()),
                ('Duration', models.IntegerField()),
                ('Description', models.TextField()),
                ('ImbdRating', models.FloatField()),
                ('AgeLimit', models.IntegerField()),
                ('Genre', models.CharField(max_length=50)),
                ('Poster', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShowTitle', models.CharField(max_length=100)),
                ('ReleaseDate', models.DateField()),
                ('Description', models.TextField()),
                ('ImbdRating', models.FloatField()),
                ('AgeLimit', models.IntegerField()),
                ('Genre', models.CharField(max_length=50)),
                ('Poster', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ShowCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.actor')),
                ('ShowId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.show')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SeasonNumber', models.IntegerField()),
                ('NumberOfEpisodes', models.IntegerField()),
                ('ShowId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.show')),
            ],
        ),
        migrations.CreateModel(
            name='MovieDownloadLink',
            fields=[
                ('DownloadLink', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Resolution', models.IntegerField()),
                ('Language', models.CharField(max_length=100)),
                ('MovieId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.actor')),
                ('MovieId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.movie')),
            ],
        ),
        migrations.CreateModel(
            name='EpisodeDownloadLink',
            fields=[
                ('DownloadLink', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Resolution', models.IntegerField()),
                ('Language', models.CharField(max_length=100)),
                ('EpisodeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.episode')),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='SeasonId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.season'),
        ),
    ]
