# Generated by Django 4.1.4 on 2022-12-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='ReleaseDate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='show',
            name='ReleaseDate',
            field=models.IntegerField(),
        ),
    ]
