# Generated by Django 4.1.4 on 2023-01-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_movie_releasedate_alter_show_releasedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Poster',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='show',
            name='Poster',
            field=models.URLField(),
        ),
    ]
