# Generated by Django 4.1.4 on 2023-01-11 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0003_alter_movie_poster_alter_show_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMovieDownloaded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MovieId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.movie')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
